






<nav class="navbar navbar-expand-lg fixed-top navbar-light bg-light">
  <div class="container-fluid">

    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>

        <li class="nav-item dropdown avatar">
          <a class="nav-link" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <span><img src="../<?php print_r($_SESSION['userLogin']['foto_perfil']); ?>"</span>
          </a>
          <ul class="dropdown-menu menu-box" aria-labelledby="navbarDropdown">
          <span><img src="../<?php print_r($_SESSION['userLogin']['foto_perfil']); ?>"><span class="user-name text-bold-700 ml-1"><?php echo $_SESSION['usuario']; ?></span>
          <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
      <div class="search-box">
  <input type="text" placeholder=" "/><span></span>
</div>
      </form>
    </div>
  </div>
</nav>

<!-- Modal -->
<div class="modal fade" id="camniarFotoPerfil" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      <form name="Foto" id="Foto" method="post" enctype="multipart/form-data">
        <div class="modal-body">
          <div class="Container field-wrap">
            
            <img class="imgCha" src="../<?php print_r($_SESSION['userLogin']['foto_perfil']); ?>" alt="" srcset="">

                  <input type="file" id="file" name="imgNueva">
          </div>
        </div>
      </div>
      <div class="modal-footer">
      <button type="button" class="btn btn-light" data-dismiss="modal">Cancelar</button>
          <button type="submit" class="send_foto btn btn-dark">Guardar</button>
        </div>
      </form>
    </div>
  </div>
</div>
<!-- fin modal -->

<!-- Modal editar perfil -->
<div class="modal fade" id="edit" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      <form id="formPerfil" action="#" method="post">
        <div class="modal-body">
          <div class="Container field-wrap">
            

              <input type="text" name="" id="nombres" value="<?php print_r($_SESSION['userLogin']['nombres']); ?>">
              <input type="text" name="" id="apellidos" value="<?php print_r($_SESSION['userLogin']['apellidos']); ?>">
              <input type="text" name="" id="usuario" value="<?php print_r($_SESSION['userLogin']['usuario']); ?>">
              <input type="text" name="" id="correo" value="<?php print_r($_SESSION['userLogin']['correo']); ?>">
              <input type="text" name="" id="telefono" value="<?php print_r($_SESSION['userLogin']['telefono']); ?>">
              <input type="text" name="" id="telefono" value="<?php print_r($_SESSION['userLogin']['telefono']); ?>">
              <div class="imgPerfil">
              <img src="../<?php print_r($_SESSION['userLogin']['foto_perfil']); ?>" alt="" srcset="">
              <input type="text" name="" id="" value="<?php print_r($_SESSION['userLogin']['foto_perfil']); ?>">
              <button type="button" class="cambiarFoto" data-bs-toggle="modal"> cambiar</button>
              </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
      <button type="button" class="btn btn-light" data-dismiss="modal">Cancelar</button>
          <button type="submit" id="btnEdi" class="btn btn-dark">Guardar</button>
        </div>
      </form>
    </div>
  </div>
</div>
<!-- fin modal -->