<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- boostrap 5.0 css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <!-- estilos de formulario de registro -->
    <link rel="stylesheet" href="../css/estilos_registro.css">
    <!-- formulario de login y sing -->
    <link rel="stylesheet" href="../css/estilo_login_sing.css">
    <!-- loader -->
    <link rel="stylesheet" href="../css/loader.css">
    <!-- avatar user -->
    <link rel="stylesheet" href="../css/avatar_user.css">
    <!-- box-buscar -->
    <link rel="stylesheet" href="../css/box_buscar.css">
    <!-- data tables css -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.24/datatables.min.css"/>
    <!-- tabla publicaciones -->
    <link rel="stylesheet" href="../css/tabla_publicaciones.css">
    <!-- estilos para los seleects -->
    <link rel="stylesheet" href="../css/estilos_select.css">
    <!-- estilos generales -->
    <link rel="stylesheet" href="../css/estilos.css">
    <!-- caja de publicaciones -->
    <link rel="stylesheet" href="../css/estilo_caja_publicaciones.css">
    <!-- boton abrir publicaciones -->
    <link rel="stylesheet" href="../css/boton_ver_publicacion.css">
    <!-- loader reaciones -->
    <link rel="stylesheet" href="../css/loader_reaciones.css">
    <!-- estilo para los comentario -->
    <link rel="stylesheet" href="../css/estilo_comentarios.css">
    <!-- re modal -->
    <link rel="stylesheet" href="../lib/remodal/css/remodal-default-theme.css">
    <link rel="stylesheet" href="../lib/remodal/css/remodal.css">
</head>
<body>

<?php

include_once($contenido);

?>

<!----------------------------------------------------------------------------------------------------------------------------------------
    scripts scripts scripts scripts scripts scripts scripts scripts scripts scripts scripts scripts scripts scripts scripts scripts
---------------------------------------------------------------------------------------------------------------------------------------->

<!-- boostrap 5.0 js -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
<!-- jquery 3.1.1 js -->
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script> 
<!-- formulario de login y sing js -->
<script src="../js/formulario_login_sing.js"></script>
<!-- re modal js -->
<script src="../lib/remodal/js/remodal.js"></script>
<!-- formulario de registro -->
<script src="../js/formulario_registro.js"></script>
<!-- combox geografia -->
<script src="../js/combox_geografia.js"></script>
<!-- restablecer Clave -->
<script src="../js/recuperar-clave.js"></script>
<!-- swetalert -->
<script src="//cdn.jsdelivr.net/npm/sweetalert2@10"></script>
<!-- iconos -->
<script src="https://kit.fontawesome.com/2c36e9b7b1.js" crossorigin="anonymous"></script>
<!-- box_buscar js -->
<script src="../js/box_buscar.js"></script>
<!-- datos del usurio -->
<script src="../js/info_user.js"></script>
<!-- editar perfil -->
<script src="../js/editar_perfil.js"></script>
<!-- data tables -->
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.24/datatables.min.js"></script>
<!-- tabla autor libros -->
<script src="../js/tables_publicaciones/libros.js"></script>
<!-- tabla autor libros -->
<script src="../js/tables_publicaciones/imagenes.js"></script>

<!-- mostrar publicaciones -->
<script src="../js/mostrar_publicaciones/libros.js"></script>

</body>
</html>