<?php
include "menu_lector.phtml";
?>
<div class="container">
    <div class="row">
        <div class="content-select-menu">
            <select  onchange="location = this.value">
            <option value="#">Imagenes</option>
            <option value="controlador.php?sesion=3">libros</option>
            <option value="centros.php">centros</option>
            <option value="votos.php">votos</option>
            <option value="programas.php">programas</option>
            <option value="jornadas.php">jornadas</option>
            </select>
            <i></i>
        </div>
        <div class="col-lg-1">
            <button id="btnNueva_img" type="button" class="btn add_new" data-toggle="modal"><i class="far fa-plus-square"></i></button>
        </div>
    </div>
</div>
<br>

<div class="container caja">
    <div class="row">
        <div class="col-lg-12">
            <div class="table-responsive">
                <table id="tablaImg" class="table table-striped table-bordered table-condensed" style="width:100%">
                    <thead class="text-center">
                        <tr>
                            <th>#</th>
                            <th>autor</th>
                            <th>nombre Imagen</th>
                            <th>fecha de registro</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!--Modal para CRUD-->
<div class="modal fade" id="modal_add_img" data-bs-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel"></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form id="formImg" enctype="multipart/form-data">
                <div class="modal-body">
                    <div class="row" id="row_1">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <p class="label">Autor</p>
                                <input class="INput" name="autor_img" id="autor_img" required='' type='text'>
                                <label alt='Autor' placeholder='Autor de la imagen'></label>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <p class="label">Nombre</p>
                                <input class="INput" name="nombre_img" id="nombre_img" required='' type='text'>
                                <label alt='Nombre' placeholder='Nombre de la imagen'></label>
                            </div>
                        </div>
                    </div>
                    <div class="row" id="row_3">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <p class="label">Categoria</p>
                                <div class="content-select">
                                    <select name="categoria_img" id="categoria_img">
                                        <option value="0">Seleccione la categoria</option>
                                        <?php
                                        include "../modelo/categorias.php";
                                        ?>
                                    </select>
                                    <i></i>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-6">
                            <div class="form-group">
                                <p class="label">Tags</p>
                                <input class="INput" name="tags_img" id="tags_img" required='' type='text'>
                                <label alt='Tags' placeholder='Tags del libro'></label>
                            </div>
                        </div>
                    </div>
                    <div class="row" id="row_archivos">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <p class="label">Archivo Imagen</p>
                                <div class="invoiceBox">
                                    <label for="img">
                                        <div class="boxArchivo" data-text="Seleccionar Imagen">
                                            Selecione la imagen
                                        </div>
                                    </label>
                                    <input id="img" name="img" size="6000" type="file">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row" id="row_4">
                        <p class="label">Reseña de la imagen</p>
                        <div class="col-lg-10">
                            <div class="form-group">
                                <textarea name="reseña_img" id="reseña_img" class="estilotextarea3" cols="" rows=""></textarea>
                            </div>
                        </div>
                    </div>
                </div>

                <div id="loader-send-img" class="esconder loader loader--flipDelay loader--3d ">
                    <span class="loader-item">1</span>
                    <span class="loader-item">2</span>
                    <span class="loader-item">3</span>
                    <span class="loader-item">4</span>
                    <span class="loader-item">5</span>
                    <span class="loader-item">6</span>
                </div>


                <div class="modal-footer">
                    <button type="submit" id="send_img" class="btn btn-dark">Guardar</button>
                </div>
            </form>
        </div>
    </div>
</div>