<?php
include "menu_autor.phtml";
?>
<div class="container" style="margin-top: 80px;">
    <div class="row">
        <div class="content-select-menu">
            <select  onchange="location = this.value">
            <option value="#">libros</option>
            <option value="controlador.php?sesion=4">Imagenes</option>
            <option value="centros.php">centros</option>
            <option value="votos.php">votos</option>
            <option value="programas.php">programas</option>
            <option value="jornadas.php">jornadas</option>
            </select>
            <i></i>
        </div>
        <div class="col-lg-1">
            <button id="btnNuevo" type="button" class="btn add_new" data-toggle="modal"><i class="far fa-plus-square"></i></button>
        </div>
    </div>
</div>
<br>

<div class="container caja">
    <div class="row">
        <div class="col-lg-12">
            <div class="table-responsive">
                <table id="tablaLibros" class="table table-striped table-bordered table-condensed" style="width:100%">
                    <thead class="text-center">
                        <tr>
                            <th>#</th>
                            <th>autor</th>
                            <th>nombre libro</th>
                            <th>cantidad de paginas</th>
                            <th>fecha de registro</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!--Modal para CRUD-->
<div class="modal fade" id="modal_add_libro" data-bs-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel"></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form id="formLibro" enctype="multipart/form-data">
                <div class="modal-body">
                    <div class="row" id="row_1">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <p class="label">Autor</p>
                                <input class="INput" name="autor" id="autor" required='' type='text'>
                                <label alt='Autor' placeholder='Autor del libro'></label>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <p class="label">Nombre</p>
                                <input class="INput" name="nombre" id="nombre" required='' type='text'>
                                <label alt='Nombre' placeholder='Nombre del libro'></label>
                            </div>
                        </div>
                    </div>
                    <div class="row" id="row_2">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <p class="label">Volumen</p>
                                <input class="INput" name="volumen" id="volumen" required='' type='number'>
                                <label alt='volumen' placeholder='Numero volumen del libro'></label>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <p class="label">Paginas</p>
                                <input class="INput" name="paginas" id="paginas" required='' type='number'>
                                <label alt='paginas' placeholder='numero de paginas'></label>
                            </div>
                        </div>
                    </div>
                    <div class="row" id="row_3">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <p class="label">Categoria</p>
                                <div class="content-select">
                                    <select name="categoria" id="categoria">
                                        <option value="0">Seleccione la categoria</option>
                                        <?php
                                        include "../modelo/categorias.php";
                                        ?>
                                    </select>
                                    <i></i>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-6">
                            <div class="form-group">
                                <p class="label">Tags</p>
                                <input class="INput" name="tags" id="tags" required='' type='text'>
                                <label alt='Tags' placeholder='Tags del libro'></label>
                            </div>
                        </div>
                    </div>
                    <div class="row" id="row_archivos">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <p class="label">Imagen caratula</p>
                                <div class="invoiceBox">
                                    <label for="caratula">
                                        <div class="boxCaratula" data-text="Seleccionar caratula">
                                            Selecione imagen
                                        </div>
                                    </label>
                                    <input id="caratula" name="caratula" size="6000" type="file">
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <p class="label">Archivo libro</p>
                                <div class="invoiceBox">
                                    <label for="libro">
                                        <div class="boxArchivo" data-text="Seleccionar libro">
                                            Selecione el libro
                                        </div>
                                    </label>
                                    <input id="libro" name="libro" size="6000" type="file">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row" id="row_4">
                        <p class="label">Reseña del libro</p>
                        <div class="col-lg-10">
                            <div class="form-group">
                                <textarea name="reseña" id="reseña" class="estilotextarea3" cols="" rows=""></textarea>
                            </div>
                        </div>
                    </div>
                </div>

                <div id="loader-send-libro" class="esconder loader loader--flipDelay loader--3d ">
                    <span class="loader-item">1</span>
                    <span class="loader-item">2</span>
                    <span class="loader-item">3</span>
                    <span class="loader-item">4</span>
                    <span class="loader-item">5</span>
                    <span class="loader-item">6</span>
                </div>


                <div class="modal-footer">
                    <button type="submit" id="send_libro" class="btn btn-dark">Guardar</button>
                </div>
            </form>
        </div>
    </div>
</div>